### ISSUE TITLE
Separate validations for MX records and A records?

### ISSUE THREAD

**Issue by pcrglennon** [lisinge/valid_email2#118]
We're using `valid_email2` to help build a list of domains we've sent emails to, with the intent of using that to start filtering out requests to domains we know are bad.

I noticed that, under the hood, [`Address#valid_mx?` is looking for A records as well](https://github.com/lisinge/valid_email2/blob/master/lib/valid_email2/address.rb#L55), so it would return true if the domain has no MX records, but does have A records.

Why is that the case?

In our use case, we wanted to be a little more explicit with the information we store, so we keep the results of MX and A record validations separate. So we ended up writing our method instead of using `#valid_mx?`, which looks like this

```rb
def dns_validation_results
  Resolv::DNS.open do |dns|
    return {
      valid_mx_records: dns.getresources(email_address.domain, Resolv::DNS::Resource::IN::MX).size > 0,
      valid_a_records: dns.getresources(email_address.domain, Resolv::DNS::Resource::IN::A).size > 0
    }
  end
end
```

It would be useful (for us, at least) to have some sort of separate `#valid_a?` method (with a better name than that, of course). And have `#valid_mx?` return true only if there are valid MX records found, without falling back to A records.

I get that that could be a breaking change for some, so maybe for now it would make more sense to keep the same behavior for `#valid_mx?`, and just add new, more specific methods like `#valid_mx_records?` and `#valid_a_records?`? It should be possible to have those both use the same resolver (by memoization), so it shouldn't affect performance.

Is that something others would find useful? I'd be happy to open a PR, but wanted to propose the idea first, in case this is an issue that's already been discussed and resolved.

**Comment by lisinge** [comment]
Hi Peter.

The reason we are looking for an A record is because RFC5321 states that if no MX records are found, but a A record is found, then that A record should be treated as an implicit MX record.

This change was introduced in PR #101.

If you still feel the need to record them separately then i'm open to accepting a PR.

Just one question though, would we be able to make it work for your use-case by rewriting `#valid_mx?` to take an optional `allow_implicit` parameter that defaults to true. And on top of that implement `#valid_implicit_mx?` or `#valid_implicit_a?` (whichever name you think is the most appropriate) which looks for the A record?

This would not break backwards compatibility and should let you do what you are currently doing, i think.

Let me know what you think!

**Comment by pcrglennon** [comment]
Ah, that makes sense, thanks for the context!

Our use case has changed since I posted this, we're now collecting more Domain-specific DNS data,  to the point where it makes more sense to just use Resolv directly. So I'll just close this issue, rather than trying to force super-specific functionality into the gem (which we might not even be able to use, as our particular requirements are still changing, of course).

Just for the record, we are still making heavy use of the gem for the general validity logic & disposable-domain checking, and it's working very well for us!

**Comment by lisinge** [comment]
@pcrglennon that makes me happy to hear. Cheers!

**Comment by lostapathy** [comment]
@micke I just spent quite a bit of time tracking down a bug that led me here.

I appreciate the logic for having MX fall back to A records, but it would be great if we could validate strictly based on the presence of an MX and without the A record fall through.  I've track down a couple cases where the user typo's their domain and due to squatters or wildcard subdomain records the A record exists (and valid_mx?) is true, but there's no MX to receive the email.  

Since effectively all "consumer email" has an MX record defined, we intended to validate strictly on that in hopes of eliminating the typo domains with A records but no MX.

Having separate methods like valid_mx? and valid_dns? rather than optional parameters seems like it'd be more clear to me.

**Comment by micke** [comment]
@lostapathy i'm so sorry this caused you trouble. This was one of my fears when accepting the PR that introduced the implicit A record as valid MX setup.

However, as we are following SMTP standards by using the A record implicitly, I would like this to still be the default.

What do you think about accepting a `implict_a` parameter (that defaults to `true`) to the `valid_mx?` and to the ActiveRecord validation? Would that solve your issues?

I'm quite busy right now but a PR would be greatly appreciated!

**Comment by lostapathy** [comment]
@micke I'm working on a PR for you.  I'm kinda wrestling with the param name, though.  How do you feel about adding a `strict_mx` or `mx_only` parameter to the validator?  I feel like that's maybe a little more discoverable than `implicit_a`

**Comment by micke** [comment]
@lostapathy That's awesome! I appreciate it

Yeah, i like the `strict_mx` param name!
