### ISSUE TITLE
Consider a more permissive mail gem dependency?

### ISSUE THREAD

**Issue by bobthecow** [lisinge/valid_email2#16]
[mail's current version is 2.6.3](https://rubygems.org/gems/mail), but valid_email2 depends on `~> 2.5.4` — or, `>= 2.5.4, < 2.6.0`. But v1.0.0 of valid_email2 just depended on `> 0`, so when resolving dependencies, Bundler just opts to install valid_email2 v1.0.0.

If v1.0.0 works with mail v2.6.3 (as it seems to, in my app), I can't imagine the current version would be any worse. Can we change the dependency version to `~> 2.5` or `~>2.5, >=2.5.4` or something?

Thanks :)

**Comment by lisinge** [comment]
I've previously discussed compatability with v2.6 of the mail gem in #12.
We used the private method `Mail::Address#tree` which was removed in v2.6. It was really silly to use a private method and it was just waiting to brake.

It's possible that you haven't been able to hit valid_email2 when you've tested with v1.0.0 because it shouldn't be compatible with mail v2.6 either as we used `#tree` in that version too.

I removed the use of the `#tree` method and changed the dependency on the mail gem to `~> 2.5` and pushed it to rubygems. Please try it out and report back if you have any problems.

Thanks for the input it's always apreciated!

**Comment by bobthecow** [comment]
Awesome. It's working great. Thanks for the fast turnaround!
